name: Generate daily TradingAgents reports

on:
  schedule:
    - cron: "15 0 * * *"  # daily at 00:15 UTC
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    env:
      # LLM provider envs (expect OPENAI_API_KEY or others in repo/user secrets)
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
      GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
      # Optional data provider keys
      FINNHUB_API_KEY: ${{ secrets.FINNHUB_API_KEY }}
      REDIS_URL: ${{ secrets.REDIS_URL }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install dependencies
        run: |
          python -m pip install -r requirements.txt

      - name: Determine date (UTC)
        id: date
        run: echo "date=$(date -u +%F)" >> $GITHUB_OUTPUT

      - name: Generate reports for top S&P 500 tickers
        run: |
          set -e
          # Static top-10 S&P 500 by market cap (adjust as needed)
          TICKERS=(AAPL MSFT NVDA GOOGL AMZN META AVGO LLY BRK.B JPM)
          DATE="${{ steps.date.outputs.date }}"
          for T in "${TICKERS[@]}"; do
            echo "Running reports for $T on $DATE"
            python -m gen_reports --ticker "$T" --date "$DATE" --locales EN,KO --translate || echo "gen_reports failed for $T" >&2
          done

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add reports eval_results || true
          if ! git diff --cached --quiet; then
            git commit -m "chore(reports): daily generation for ${{ steps.date.outputs.date }}"
            git push
          else
            echo "No changes to commit"
          fi


